[pipeline]
  [pipeline.input]
  type = "csv"
  file = "data/test.csv"

  [[pipeline.steps]]
  [pipeline.steps.filter]
  column = "amount"
  condition = ">1000"

  [[pipeline.steps]]
  [pipeline.steps.group_by]
  column = "category"

  [pipeline.output]
  type = "json"
  file = "data/result.json"