pipeline:
  input:
    type: csv
  steps:
    - filter:
        column: product
        condition: "is 'Laptop'"
    - filter:
        column: product
        condition: "contains 'Phone'"
  output:
    type: csv
    file: data/result_pipeline_1.csv
