pipeline:
  input:
    type: csv
  steps:
    - filter:
        column: amount
        condition: "= 1500"
    - group_by:
        column: category
        aggregation:
          amount: "mean"
  output:
    type: json
    file: data/result_pipeline_2.json